server:
  port: 8080
spring:
  redis:
    host: Redis
    port: 6379
    timeout: 20
    password: ENC(ZB7jWXUgNnDyQvcdPkfL+oE10CWPacrjx1gr3975bn7JTwgM5xH/LwIGn0UTlY10)
  data:
    mongodb:
      uri: ENC(bHNVOJSbnG4amniQJ8j5VGVgaVQ6L4dyWXn/KiDaWWb4MnqUa3ZmHsEKm7RJLqFtHwEPmWKiKx/g2kVE6DhBeK2xNmZhIOE75gYv/IiE5W0=)
#      host: mongo
#      port: 27017
#      database: chess
#      username: ENC(vP0ghtRf6x6XOA1Hj1nMdxYuDiV8/u4uKU8AizIIrfx9DZudPOQrUFz6xdVpPyUW)
#      password: ENC(w2fu9hTNo3cS4E7XUIVbrZ78rNYFXCEgY3yuvfJjdfROoNOfKQjFFB3f37GkkAeT)

jwt:
  secretKey:
    ENC(KmqxTG8MaxW4NhHwIzB9gngw0LgN0SiRuts0b6CNZRx5pJWAo0d/U/VQ3H7buN0H0rUH5y7bUsuLwU5EOLSyeOnl/cXb1Dh9cEGZXaF0ic8=)
  accessExpiration: 1800000
  refreshExpiration: 604800000
jasypt:
  encryptor:
    bean: jasyptEncryptorAES
